### ISSUE TITLE
Update locator_ros_bridge team membership.

### ISSUE THREAD

**Issue by slaible** [ros-gbp/locator_ros_bridge-release#1]
Hello :) Could you please add the users @kfabian and @syyuen to the locator_ros_bridge team? Thanks a lot!

**Comment by sloretz** [comment]
@slaible FYI in case you're not getting notifications from the release repo

**Comment by slaible** [comment]
@sloretz How can I add people to this release repo, analogous to the Terraform files in ROS 2: https://github.com/ros2-gbp/ros2-gbp-github-org/commit/7317433a396c96e2f7f45b18956748744dd52a18

**Comment by sloretz** [comment]
Oops, @nuclearsandwich pointed out that you were the one who opened the ticket, so you didn't need an extra ping 🙃 

It looks like the ROS 1 process is manual. I created a team and invited the three of you to it. [locator_ros_bridge-maintainers](https://github.com/orgs/ros-gbp/teams/locator_ros_bridge-maintainers). Accepting the invite should grant maintainer permissions.

**Comment by slaible** [comment]
@sloretz No worries :smile: Thanks a lot!
